Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/bionic64"
    web.vm.synced_folder "./web_data", "/vagrant_web"
    web.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    end
  end
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/bionic64"
    db.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    end
  end
end