Vagrant.configure("2") do |config|
config.vm.define "Environment 1" do |Environment 1|
        Environment 1.vm.box = ""
        Environment 1.vm.hostname = "HostEnvironment1"
        Environment 1.vm.provider "virtualbox" do |vb|
            vb.name = "Environment 1"
            vb.memory = 1024
            vb.cpus = 1
        end
Environment 1.vm.synced_folder "C:/Users/pabfl/Downloads/noborrar", "aaa"
Environment 1.vm.provision "file", source: "C:/Games/betterjoy/BetterJoyForCemu.exe", destination: "a"
Environment 1.vm.provision "file", source: "C:/Users/pabfl/Desktop/dev", destination: "b"
Environment 1.vm.provision "shell", path: "C:/Users/pabfl/Desktop/kk/jueguito/pc/bats/eth.bat"
    end
config.vm.define "Environment 2" do |Environment 2|
        Environment 2.vm.box = ""
        Environment 2.vm.hostname = "HostEnvironment2"
        Environment 2.vm.provider "virtualbox" do |vb|
            vb.name = "Environment 2"
            vb.memory = 1024
            vb.cpus = 1
        end
Environment 2.vm.synced_folder "C:/Users/pabfl/Documents", "bbb"
Environment 2.vm.provision "file", source: "C:/Games/Balatro.v1.0.1n-P2P/Balatro Mod Manager/BMM.exe", destination: "ccc"
Environment 2.vm.provision "file", source: "C:/Users/pabfl/Desktop/ASIR", destination: "ddd"
Environment 2.vm.provision "shell", path: "C:/Users/pabfl/Desktop/kk/jueguito/pc/bats/eth.bat"
    end
config.vm.define "Environment 3" do |Environment 3|
        Environment 3.vm.box = ""
        Environment 3.vm.hostname = "HostEnvironment3"
        Environment 3.vm.provider "virtualbox" do |vb|
            vb.name = "Environment 3"
            vb.memory = 1024
            vb.cpus = 1
        end
Environment 3.vm.synced_folder "C:/Users/pabfl/Desktop/a_mano", "eee"
Environment 3.vm.provision "file", source: "C:/Users/pabfl/Desktop/a_mano/propuestadeproyecto_pabloferlo.pdf", destination: "aaa"
Environment 3.vm.provision "file", source: "C:/Users/pabfl/Desktop/a_mano/main", destination: "basdsa"
Environment 3.vm.provision "shell", path: "C:/Users/pabfl/Desktop/kk/jueguito/pc/bats/eth.bat"
    end
end