Vagrant.configure("2") do |config|
    config.vm.define "test test" do |test test|
        test test.vm.box = "hashicorp/bionic64"
        test test.vm.hostname = "test test"
        test test.vm.provider "virtualbox" do |vb|
            vb.name = "test test"
            vb.memory = 1024
            vb.cpus = 1
        end


    end
end